-- BOARD TABLE DROP & CREATE
DROP SEQUENCE BOARD_SEQ;
CREATE SEQUENCE BOARD_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
DROP TABLE BOARD;
CREATE TABLE BOARD (
    bID NUMBER(6) PRIMARY KEY,
    bNAME VARCHAR2(50) NOT NULL,    --�ۼ��� �̸�
    bTITLE VARCHAR2(100) NOT NULL,
    bCONTENT VARCHAR2(1000),
    bDATE DATE DEFAULT SYSDATE NOT NULL,    -- �ۼ�����
    bHIT NUMBER(6) DEFAULT 0 NOT NULL,  -- ��ȸ��
    bGROUP NUMBER(6) NOT NULL,  -- �� �׷�
    bSTEP NUMBER(6) NOT NULL,   -- �� �׷쳻 ��� ����
    bINDENT NUMBER(6) NOT NULL, -- �鿩����
    bIP VARCHAR2(20) NOT NULL
);
-- DUMMY DATA
SELECT * FROM BOARD;
INSERT INTO BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (BOARD_SEQ.NEXTVAL, '�ڹڹ�', '��1', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
INSERT INTO BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (BOARD_SEQ.NEXTVAL, '�ŽŽ�', '��2', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
SELECT * FROM BOARD
    ORDER BY bGROUP DESC, BSTEP;
INSERT INTO BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (BOARD_SEQ.NEXTVAL, '����', '��1-1', '�����', 1, 1, 1, '192.168.10.30');
-- DAO�� �� QUERY
-- �۸�� (startRow ~ endRow)
SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP;    -- �� ��� ����
SELECT *
    FROM (select ROWNUM RN, A.* FROM (SELECT * FROM BOARD ORDER BY BGROUP DESC, BSTEP) A)
    WHERE RN BETWEEN 2 AND 3;
            
-- ��ü �� ����
SELECT COUNT(*) CNT FROM BOARD;
-- ���۾���
INSERT INTO BOARD (bID, bNAME, bTITLE, bCONTENT, bGROUP, bSTEP, bINDENT, bIP)
    VALUES (BOARD_SEQ.NEXTVAL, '�ڹڹ�', '��1', '-', BOARD_SEQ.CURRVAL, 0, 0, '192.168.10.30');
-- bID�� ��ȸ�� �ø���
UPDATE BOARD
    SET bHIT = bHIT+1
    WHERE bID ='1';
-- �� �󼼺���(bID�� DTO��������)
SELECT * FROM BOARD WHERE bID='1';
-- �亯�� ������ STEP A (������ �亯���� ��� ������ +1)  : 1������ �亯�� �� ����
SELECT * FROM BOARD WHERE bGROUP = 1;   -- 1�� �� GROUP ���
UPDATE BOARD SET bSTEP = bSTEP+1 WHERE BGROUP=1 AND BSTEP>0;
-- �亯�� ����
INSERT INTO BOARD (BID, BNAME, BTITLE, BCONTENT, BGROUP, BSTEP, BINDENT, BIP)
    VALUES (BOARD_SEQ.NEXTVAL, '�ڴ�', '��1-2', NULL, 1, 1, 1, '127.0.0.1');
-- �� ����
UPDATE BOARD 
    SET BNAME ='������',
        BTITLE ='������',
        BCONTENT = '�����Ⱥ���',
        BIP = '192.1.1.1'
    WHERE BID=2;
-- �� ����
DELETE FROM BOARD WHERE BID=2;
commit;