--[XI]인덱스 : 조회를 빠르게 하는 인덱스
SELECT * FROM USER_INDEXES; --딕셔너리뷰에서 SCOTT이 소유한 인덱스 정보
DESC EMP;
SELECT * FROM EMP;

DROP TABLE EMP01;
CREATE TABLE EMP01 AS SELECT * FROM EMP;    --EMP내용과 같은 EMP01생성
INSERT INTO EMP01 SELECT * FROM EMP01;  --13번 수행   (114,688개)
SELECT TO_CHAR(COUNT(*), '9,999,999') FROM EMP01;
INSERT INTO EMP01 (EMPNO, ENAME) VALUES (1111,'HONG');
INSERT INTO EMP01 SELECT * FROM EMP01;  --'HONG'이 더 많아지게(3번) --->(917,512개)
--인덱스 생성 전 조회
SELECT * FROM EMP01 WHERE ENAME = 'HONG';   --0.015초
--인덱스 생성(EMP01테이블의 ENAME)하고 조회
CREATE INDEX IDX_EMP01_ENAME ON EMP01(ENAME);   --인덱스 생성 : 0.375초
SELECT * FROM EMP01 WHERE ENAME = 'HONG';   --인덱스 생성 후 : 0.00..초
SELECT * FROM USER_INDEXES WHERE INDEX_NAME = 'IDX_EMP01_ENAME';   
COMMIT; --90만개 행
INSERT INTO EMP01 SELECT * FROM EMP01;  --인덱스 생성 후 INSERT 속도 : 21초
DROP INDEX IDX_EMP01_ENAME;
ROLLBACK;   --90만개 행(취소속도 : 10.3초)
SELECT TO_CHAR(COUNT(*), '9,999,999') FROM EMP01;
DROP INDEX IDX_EMP01_ENAME;
INSERT INTO EMP01 SELECT * FROM EMP01;  --인덱스 제거 후 INSERT 속도 : 4.187초









