--[XII] TRANSACTION 명령어 : COMMIT(트랜잭션반영); ROLLBACK(트랜잭션 취소); SAVEPOINT(트랜잭션 분할);
DROP TABLE DEPT01;
CREATE TABLE DEPT01 AS SELECT * FROM DEPT;
SELECT * FROM DEPT01;   --10, 20, 30, 40
DELETE FROM DEPT01;
SELECT * FROM DEPT01;   --데이터 베이스에서 삭제된게 아님, 트랜잭션에서 삭제된 것
ROLLBACK;   --새로운 트랜잭션 시작(SELECT는 트랜잭션에 안쌓임, DELETE, INSERT 쌓임)
SELECT * FROM DEPT01;   --COMMIT하면 트랜잭션의 과정이 들어가는 것
DELETE FROM DEPT01 WHERE DEPTNO=40;
COMMIT;
--일부 트랜잭션만 취소시엔(SAVEPOINT로 이름지정해서)
--새로운 트랜잭션 시작
SELECT * FROM DEPT01;   --10, 20, 30
DELETE FROM DEPT01 WHERE DEPTNO = 30;
SELECT * FROM DEPT01;   --10, 20
SAVEPOINT C1;   --C1지점 : 10, 20번 부서
DELETE FROM DEPT01 WHERE DEPTNO=20;
SELECT * FROM DEPT01;   --10
SAVEPOINT C2;   --C2지점 : 10번 부서
DELETE FROM DEPT01 WHERE DEPTNO = 10;
SELECT * FROM DEPT01;   --데이터 없음
ROLLBACK TO C2; --C1먼저하면 C2가 날아감ㅎㅎ
SELECT * FROM DEPT01;   --10번부서만 남아있다!
ROLLBACK TO C1;
SELECT * FROM DEPT01;
COMMIT;
SELECT * FROM DEPT01;

