<<<<<<< HEAD
--scott2로 들어와 딕셔너리 뷰 확인
SHOW USER;
SELECT * FROM USER_TABLES;  --SCOTT2가 가지고 있는 테이블(아무것도 없음)
SELECT * FROM ALL_TABLES;   --SCOTT2가 접근가능한 테이블
SELECT * FROM ALL_TABLES WHERE TABLE_NAME IN ('DEPT', 'EMP'); --(EMP, DEPT에서 가져온것)
SELECT * FROM SCOTT.EMP E, SCOTT.DEPT D WHERE E.DEPTNO = D.DEPTNO;
EXIT;






=======
--scott2로 들어와 딕셔너리 뷰 확인
SHOW USER;
SELECT * FROM USER_TABLES;  --SCOTT2가 가지고 있는 테이블(아무것도 없음)
SELECT * FROM ALL_TABLES;   --SCOTT2가 접근가능한 테이블
SELECT * FROM ALL_TABLES WHERE TABLE_NAME IN ('DEPT', 'EMP'); --(EMP, DEPT에서 가져온것)
SELECT * FROM SCOTT.EMP E, SCOTT.DEPT D WHERE E.DEPTNO = D.DEPTNO;
EXIT;






>>>>>>> 96d58a64e5ebb5b1e4ae407f3b35890afe1e7606
