--[VIII] SEQUENCE : 순차번호 생성기, 대부분 인위적인 PK 사용 용도
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ  --시퀀스 만들기
    START WITH 1   --DEFAULT값 = 1
    INCREMENT BY 1  --1씩 증가, DEFAULT값 = 1
    MAXVALUE 9999
    MINVALUE 1  --DEFAULT값 = 1
    NOCACHE --미리 20개정도 쌓여있는 CACHE메모리를 사용하지 않겠다!
    NOCYCLE;
SELECT FRIEND_SEQ.NEXTVAL FROM DUAL; 
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;    
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(4) PRIMARY KEY,  --시퀀스 이용
    NAME VARCHAR2(10) NOT NULL,
    TEL VARCHAR2(30) UNIQUE,    --NULL허용, 유일한 값
    ADDRESS VARCHAR2(300),
    LAST_MODIFYED DATE DEFAULT SYSDATE
    );
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', NULL, '서울시 강남구');
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) 
    VALUES (FRIEND_SEQ.NEXTVAL, '홍길동', '010-9999-9999', '서울시 용산구');
SELECT * FROM FRIEND;   --에러나도 시퀀스는 증가한다!!!
INSERT INTO FRIEND (NUM, NAME, TEL, ADDRESS) VALUES ( FRIEND_SEQ.NEXTVAL, '신길동', '010-8888-8888', '서울시 영등포구');
SELECT FRIEND_SEQ.CURRVAL FROM DUAL;    --현재시퀀스값
COMMIT;

--EX.초기값 101부터 최대값 999,999까지 1씩 증가하는 test_seq 시퀀스를 생성
DROP SEQUENCE TEST_SEQ;
CREATE SEQUENCE TEST_SEQ
    START WITH 101
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
SELECT TEST_SEQ.CURRVAL FROM DUAL;  --시퀀스 현재 값이 없어서 에러
SELECT TEST_SEQ.NEXTVAL FROM DUAL;
    
--연습문제
--EX1.
DROP SEQUENCE MEMBER_SEQ;
CREATE SEQUENCE MEMBER_SEQ
    MAXVALUE 9999
    NOCACHE 
    NOCYCLE;
DROP TABLE MEMBER_LEVEL;
CREATE TABLE MEMBER_LEVEL(
    LEVELNO NUMBER(3) PRIMARY KEY,
    LEVELNAME VARCHAR2(50)
);
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    mNO NUMBER(4) PRIMARY KEY,  --시퀀스이용
    mNAME VARCHAR2(50) NOT NULL,
    mPW VARCHAR2(50),
    mEMAIL VARCHAR2(50) UNIQUE,
    mPOINT NUMBER(10) CHECK(mPOINT>=0),
    mRDATE DATE DEFAULT SYSDATE,
    LEVELNO NUMBER(3) REFERENCES MEMBER_LEVEL(LEVELNO)
    );
INSERT INTO MEMBER_LEVEL VALUES (-1, 'BLACK');
INSERT INTO MEMBER_LEVEL VALUES (0, '일반');
INSERT INTO MEMBER_LEVEL VALUES (1, '실버');
INSERT INTO MEMBER_LEVEL VALUES (2, '골드');
SELECT * FROM MEMBER_LEVEL;
SELECT * FROM MEMBER;
SELECT MEMBER_SEQ.CURRVAL FROM DUAL; 
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, LEVELNO) 
    VALUES (MEMBER_SEQ.NEXTVAL, '홍길동', 'aa', 'hong@hong.com', 0, 0);
INSERT INTO MEMBER (mNO, mNAME, mPW, mEMAIL, mPOINT, LEVELNO) 
    VALUES (MEMBER_SEQ.NEXTVAL, '신길동', 'bb', 'sin@sin.com', 1000, 1);
SELECT * FROM MEMBER;
--EX2.
    
    
    
    
    
    
    
    
    
    
    
    
    