--[IV] ¼îÇÎ¸ô ¼³°è(»ç¿ëÀÚ¸ðµå)
    --¡Ú1.MEMBER
DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    mID VARCHAR2(100) PRIMARY KEY,
    mNAME VARCHAR2(10) NOT NULL,
    mADDRESS VARCHAR2(500) NOT NULL,
    mTEL VARCHAR2(13) UNIQUE,
    mEMAIL VARCHAR2(100) UNIQUE );
    
SELECT * FROM MEMBER;

INSERT INTO MEMBER VALUES ('abc', 'È«±æµ¿', '¼­¿ï °­³²±¸', '010-1111-1111', NULL);
INSERT INTO MEMBER VALUES ('def', 'ÀüÅõ¿Õ', '¼­¿ï ¼­´ë¹®±¸', '010-2222-2222', NULL);

    --¡Ú2.ORDER
CREATE SEQUENCE ORDERS_SEQ MAXVALUE 9999 NOCACHE NOCYCLE;

DROP TABLE ORDERS;

CREATE TABLE ORDERS(
    ORDERNUM VARCHAR2(50) PRIMARY KEY,
    --oNAME VARCHAR2(10) NOT NULL,
    oADDRESS VARCHAR2(500) NOT NULL,
    oTEL VARCHAR2(13) NOT NULL,
    mID VARCHAR2(100) REFERENCES MEMBER(mID),
    oDATE DATE DEFAULT SYSDATE
);

SELECT * FROM ORDERS;

INSERT INTO ORDERS VALUES (TO_CHAR(SYSDATE, 'RRMMDD')||TRIM(TO_CHAR(ORDERS_SEQ.NEXTVAL, '0000')) , '°æ±âµµ °úÃµ', '010-3333-3333', 'abc', SYSDATE);

    --¡Ú3.PRODUCT
DROP TABLE PRODUCT;

CREATE TABLE PRODUCT(
    pCODE VARCHAR2(10) PRIMARY KEY,
    pNAME VARCHAR2(100),
    pPRICE NUMBER(10),
    pQTY NUMBER(10)
);

SELECT * FROM PRODUCT ORDER BY pCODE;

INSERT INTO PRODUCT VALUES ('A1', '¸ÆÁÖ', 3000, '10');
INSERT INTO PRODUCT VALUES ('A2', '¼ÒÁÖ', 2000, '10');
INSERT INTO PRODUCT VALUES ('B1', '¶¥Äá', 3500, '10');
INSERT INTO PRODUCT VALUES ('B2', '¿ÀÂ¡¾î', 5000, '10');
INSERT INTO PRODUCT VALUES ('C1', '±âÀú±Í', 7000, '10');

    --¡Ú4.CART
CREATE SEQUENCE CART_SEQ;    
    
DROP TABLE CART;

CREATE TABLE CART(
    cNO NUMBER(10) PRIMARY KEY,
    mID VARCHAR2(100) REFERENCES MEMBER(mID),
    pCODE VARCHAR2(10) REFERENCES PRODUCT(pCODE),
    cQTY NUMBER(10)
);

SELECT * FROM CART;

INSERT INTO CART VALUES(CART_SEQ.NEXTVAL, 'abc', 'A1', 2);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL, 'abc', 'B1', 1);
INSERT INTO CART VALUES(CART_SEQ.NEXTVAL, 'abc', 'C1', 1);

    --¡Ú5.ORDER_DETAIL
CREATE SEQUENCE ORDER_DETAIL_SEQ;

DROP TABLE ORDER_DETAIL;

CREATE TABLE ORDER_DETAIL(
    odNO NUMBER(10) PRIMARY KEY,
    ORDERNUM VARCHAR2(50) REFERENCES ORDERS(ORDERNUM),
    mID VARCHAR2(100) REFERENCES MEMBER(mID),
    pCODE VARCHAR2(10) REFERENCES PRODUCT(pCODE),
    odQTY NUMBER(10) NOT NULL,
    odPRICE NUMBER(10)
);

SELECT * FROM ORDER_DETAIL;
ROLLBACK;
INSERT INTO ORDER_DETAIL VALUES(ORDER_DETAIL_SEQ.NEXTVAL, '2204190016', 'abc', 'A1', 2, 2*(SELECT PPRICE FROM PRODUCT WHERE PCODE='A1'));
INSERT INTO ORDER_DETAIL VALUES(ORDER_DETAIL_SEQ.NEXTVAL, '2204190016', 'abc', 'B1', 1, 1*(SELECT PPRICE FROM PRODUCT WHERE PCODE='B1'));
INSERT INTO ORDER_DETAIL VALUES(ORDER_DETAIL_SEQ.NEXTVAL, '2204190016', 'abc', 'C1', 1, 1*(SELECT PPRICE FROM PRODUCT WHERE PCODE='C1'));

SELECT ORDERNUM, mNAME, oADDRESS, oTEL, oDATE
    FROM ORDERS O, MEMBER M
    WHERE O.mID=M.mID;
SELECT P.pCODE, pNAME, pPRICE, odQTY, NVL(odPRICE,0)
    FROM ORDER_DETAIL OD, PRODUCT P
    WHERE P.pCODE = OD.pCODE;

