DROP SEQUENCE CUS_SEQ;
CREATE SEQUENCE CUS_SEQ
    MAXVALUE 999
    NOCACHE
    NOCYCLE;
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    cID NUMBER(30) PRIMARY KEY,
    cPHONE VARCHAR2(30) UNIQUE NOT NULL,
    cNAME VARCHAR2(10) NOT NULL,
    cPOINT NUMBER(10) DEFAULT 1000
);
INSERT INTO CUSTOMER VALUES(CUS_SEQ.NEXTVAL, '010-9999-9999', '홍길동', 1000);
INSERT INTO CUSTOMER VALUES(CUS_SEQ.NEXTVAL, '010-6666-7777', '홍길동', 0);
INSERT INTO CUSTOMER VALUES(CUS_SEQ.NEXTVAL, '010-8888-9999', '신길동', 2000);
COMMIT;
--회원가입
INSERT INTO CUSTOMER (cID, cPHONE, cNAME) VALUES(CUS_SEQ.NEXTVAL, ?, ?);
--폰조회(4자리, 전체)
SELECT cNAME, cPHONE, cPOINT
    FROM CUSTOMER
    WHERE cPHONE LIKE '%'||'9999';
--전체출력
SELECT *
    FROM CUSTOMER
    ORDER BY cPOINT DESC;
