--1. EMP 에 저장된 사원 중 10번 부서 소속 사원의 정보를 추가한다
CREATE TABLE SAM01(
    EMPNO NUMBER(4),     
    ENAME VARCHAR2(10),  
    JOB VARCHAR2(9), 
    SAL NUMBER(7,2),
    PRIMARY KEY(EMPNO) ); 
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1000, 'APPLE', 'POLICE', 10000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1010, 'BANANA', 'NURSE', 15000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1020, 'ORANGE', 'DOCTOR', 10000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1030, 'VERY', NULL, 10000);
INSERT INTO SAM01 (EMPNO, ENAME, JOB, SAL) VALUES (1040, 'CAT', NULL, 10000);
INSERT INTO SAM01 SELECT EMPNO, ENAME, JOB, SAL FROM EMP WHERE DEPTNO='10';
COMMIT;

SELECT * FROM SAM01;

DROP TABLE SAM01;

CREATE TABLE SAM01(
    EMPNO NUMBER(4) CONSTRAINT SAM_PK PRIMARY KEY,     --제약조건 이름 지정
    ENAME VARCHAR2(10),  
    JOB VARCHAR2(9), 
    SAL NUMBER(7,2)); 
SELECT * FROM USER_CONSTRAINTS;

--SAM01 테이블에서 JOB이 정해지지 않은 사원을 삭제
SELECT * FROM SAM01;
DELETE FROM SAM01 WHERE JOB IS NULL;
