-- 테이블 생성
DROP TABLE MAJORS;
CREATE TABLE MAJORS(
    mCODE NUMBER(2) PRIMARY KEY,
    mNAME VARCHAR2(50) NOT NULL
);
DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ
    MAXVALUE 9999
    NOCACHE 
    NOCYCLE;

DROP TABLE STUDENT;
CREATE TABLE STUDENT(
    sNO NUMBER(30) PRIMARY KEY,
    sNAME VARCHAR2(50) NOT NULL,
    mCODE NUMBER(2) REFERENCES MAJORS(mCODE) NOT NULL,
    SCORE NUMBER(10) DEFAULT 0 CHECK (SCORE BETWEEN 0 AND 100),
    sEXPEL NUMBER(1) DEFAULT 0 CHECK (sEXPEL IN(0,1))
);
-- 더미데이터
ROLLBACK;
SELECT * FROM MAJORS;
SELECT * FROM STUDENT;
INSERT INTO MAJORS VALUES (1, '빅데이터학');
INSERT INTO MAJORS VALUES (2, '경영정보학');
INSERT INTO MAJORS VALUES (3, '컴퓨터공학');
INSERT INTO MAJORS VALUES (4, '국어국문학');
INSERT INTO MAJORS VALUES (5, '인공지능학');
INSERT INTO MAJORS VALUES (6, '스포츠학');
INSERT INTO MAJORS VALUES (62, '유기소재공학');
delete from student where sname = '깜찍유진';
commit;
DESC SALGRADE;
INSERT INTO STUDENT VALUES ( EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '박지원', 62, 100, 0);
INSERT INTO STUDENT VALUES ( EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '다솜씌', 2, 100, 0);
INSERT INTO STUDENT VALUES ( EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '최최진', 3, 90, 0);
INSERT INTO STUDENT VALUES ( EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '깜찍유진', 4, 99, 0);
INSERT INTO STUDENT VALUES ( EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '오오동', 6, 88, 0);
INSERT INTO STUDENT VALUES ( EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), '박지원', 62, 16, 0);
--0번. 첫화면 전공이름 컴보박스에 추가
SELECT mNAME
    FROM MAJORS;
--1번. 학번검색
SELECT sNO, sNAME, mNAME, SCORE
    FROM STUDENT S, MAJORS M
    WHERE S.mCODE = M.mCODE AND sNO = '2022001';

--2번. 이름검색
SELECT sNO, sNAME, mNAME, SCORE
    FROM STUDENT S, MAJORS M
    WHERE S.mCODE = M.mCODE AND sName = '박지원';

--3번. 전공검색
SELECT sNO, sNAME, mNAME, SCORE
    FROM STUDENT S, MAJORS M
    WHERE S.mCODE = M.mCODE AND mNAME = '유기소재공학';

--4번. 학생입력
INSERT INTO STUDENT VALUES (EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), 'sNAME', mCODE, SCORE, sEXPEL);

INSERT INTO STUDENT VALUES (EXTRACT(YEAR FROM SYSDATE)||TRIM(TO_CHAR(STUDENT_SEQ.NEXTVAL, '000')), 'sNAME',
    (select mcode from majors where mname='유기소재공학'), 22, 0);
    rollback;
--5번. 학생수정
UPDATE STUDENT SET sNAME = ?, SCORE=?, mNO = (SELECT mNO FROM MAJORS WHERE mNAME = ?) WHERE sNO = ?;

--6번. 학생 출력
SELECT ROWNUM "RANK", R.*
    FROM (SELECT sNAME||'('||sNO||')' sNAME, mNAME||'('||S.mCODE||')' mNAME, SCORE FROM STUDENT S, MAJORS M WHERE S.mCODE = M.mCODE ORDER BY SCORE DESC) R;
    
--7번. 제적자 출력
SELECT sNO, sNAME, mNAME, SCORE
    FROM STUDENT S, MAJORS M
    WHERE S.mCODE = M.mCODE AND sexpel=1;
--8.제적처리
UPDATE STUDENT SET SEXPEL = 1 WHERE sNO ='2022001';

commit;
