-- table
DROP TABLE CUSTOMER;
CREATE TABLE CUSTOMER(
    cID VARCHAR2(50) PRIMARY KEY,
    cPW VARCHAR2(50) NOT NULL,
    cNAME VARCHAR2(50) NOT NULL,
    cEMAIL VARCHAR2(50),
    cFILE VARCHAR2(50),
    cADDRESS VARCHAR2(250),
    cBIRTH DATE NOT NULL,
    cRDATE DATE DEFAULT SYSDATE
);
DROP TABLE ADMIN;
CREATE TABLE ADMIN(
    aID VARCHAR2(50) PRIMARY KEY,
    aPW VARCHAR2(50) NOT NULL,
    aNAME VARCHAR2(50) NOT NULL
);
DROP SEQUENCE FB_SEQ;
CREATE SEQUENCE FB_SEQ
    MAXVALUE 99999
    NOCACHE
    NOCYCLE;
DROP TABLE FILEBOARD;
CREATE TABLE FILEBOARD(
    fNUM NUMBER(7) PRIMARY KEY, 
    cID VARCHAR2(50) REFERENCES CUSTOMER(cID), 
    aID VARCHAR2(50) REFERENCES ADMIN(aID), 
    fSUBJECT VARCHAR2(250) NOT NULL,   
    fCONTENT VARCHAR2(4000),    
    fFILENAME VARCHAR2(50), 
    fPW VARCHAR2(50) NOT NULL,  
    fHIT NUMBER(7) DEFAULT 0 NOT NULL,   
    fREF NUMBER(7) NOT NULL,    
    fRE_STEP NUMBER(7) NOT NULL,    
    fRE_LEVEL NUMBER(7) NOT NULL,   
    fIP VARCHAR2(50) NOT NULL,  
    fRDATE DATE DEFAULT SYSDATE NOT NULL
);
COMMIT;
