-- MEMBER
DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    mID VARCHAR2(30) PRIMARY KEY,
    mPW VARCHAR2(30) NOT NULL,
    mNAME VARCHAR2(30) NOT NULL,
    mEMAIL VARCHAR2(30),
    mPHOTO VARCHAR2(30),
    mBIRTH DATE,
    mADDRESS VARCHAR2(30),
    mRDATE DATE DEFAULT SYSDATE NOT NULL
);
SELECT * FROM MEMBER;
-- ADMIN
DROP TABLE ADMIN CASCADE CONSTRAINTS;
CREATE TABLE ADMIN(
    aID VARCHAR2(30) PRIMARY KEY,
    aPW VARCHAR2(30) NOT NULL,
    aNAME VARCHAR2(30) NOT NULL
);
-- FILEBOARD
DROP SEQUENCE FBOARD_SEQ;
CREATE SEQUENCE FBOARD_SEQ
    MAXVALUE 999999
    NOCACHE
    NOCYCLE;
DROP TABLE FILEBOARD;
CREATE TABLE FILEBOARD(
    fID NUMBER(6) PRIMARY KEY,
    mID VARCHAR2(30) REFERENCES MEMBER (mID),
    fTITLE VARCHAR2(100) NOT NULL,
    fCONTENT VARCHAR2(4000),
    fFILENAME VARCHAR2(100),
    fRDATE DATE DEFAULT SYSDATE NOT NULL,
    fHIT NUMBER(6),
    fGROUP NUMBER(6) NOT NULL,
    fSTEP NUMBER(6) NOT NULL,
    fINDENT NUMBER(6) NOT NULL,
    fIP VARCHAR2(30)
);
