--TABLE DROP & CREATE
--시퀀스
DROP SEQUENCE FRIEND_SEQ;
CREATE SEQUENCE FRIEND_SEQ
    MAXVALUE 9999
    NOCACHE
    NOCYCLE;   
--테이블
DROP TABLE FRIEND;
CREATE TABLE FRIEND(
    NUM NUMBER(5) PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PHONE1 VARCHAR2(5),
    PHONE2 VARCHAR2(5),
    PHONE3 VARCHAR2(5)
);

SELECT * FROM FRIEND;
INSERT
    INTO FRIEND (NUM, NAME, PHONE1, PHONE2, PHONE3)
    VALUES(FRIEND_SEQ.NEXTVAL, '박박박', '010', '9999', '9999');
COMMIT;
SELECT * FROM FRIEND
    WHERE NAME LIKE '%'||'다'||'%' AND (PHONE1 LIKE '%'||'0'||'%' OR PHONE2 LIKE '%8%' OR PHONE3 LIKE '%9%');