-- DAO query
-- 전체 list
SELECT EMPNO, ENAME, JOB, NVL(MGR, 0) MGR, HIREDATE, SAL, NVL(COMM, 0) COMM, DEPTNO 
    FROM EMP;
-- 검색
SELECT EMPNO, ENAME, JOB, NVL(MGR, 0) MGR, HIREDATE, SAL, NVL(COMM, 0) COMM, DEPTNO FROM EMP
    WHERE ENAME LIKE '%'||UPPER('a')||'%'
        AND JOB LIKE '%'||UPPER('E')||'%';